using Demo.Application.Features.Users.Interfaces;
using Demo.Application.Features.Users.Models;
using Microsoft.AspNetCore.Identity;
using System.Text;

namespace Demo.Application.Features.Users.Infrastructure;

public class IdentityUserRepository(UserManager<AppUser> userManager, DemoDbContext context, ILogger<IdentityUserRepository> logger) : IUserRepository
{
    /// <summary>
    /// Gets users matching the ids
    /// </summary>
    /// <param name="ids">User ids to retrieve</param>
    /// <returns>List of AppUser</returns>
    public async Task<List<AppUser>> GetUsersAsync(List<string> ids)
    {
        logger.LogDebug($"Params: # of UserIds={ids.Count}");
        if (!ids.Any()) return [];

        List<AppUser> users = await userManager.Users
            .Where(u => ids.Contains(u.Id))
            .OrderBy(u => u.LastName).ThenBy(u => u.FirstName)
            .ToListAsync();

        return users;
    }

    /// <summary>
    /// Gets a user by their ID.
    /// </summary>
    /// <param name="id">ID of the user</param>
    /// <returns>AppUser, or NULL if not found</returns>
    public async Task<AppUser?> GetUserByIdAsync(string id)
    {
        logger.LogDebug($"Params: id={id}");

        AppUser? user = await userManager.FindByIdAsync(id);

        return user;
    }

    /// <summary>
    /// Gets a user by their email.
    /// </summary>
    /// <param name="email">Email of the user</param>
    /// <returns>AppUser, or NULL if not found</returns>
    public async Task<AppUser?> GetUserByEmailAsync(string email)
    {
        logger.LogDebug($"Params: email={email}");

        AppUser? user = await userManager.FindByEmailAsync(email);

        return user;
    }

    /// <summary>
    /// Gets the user's claims
    /// </summary>
    /// <param name="user">User</param>
    /// <returns>List of user's claims</returns>
    public async Task<IList<Claim>> GetUserClaimsAsync(AppUser user)
    {
        logger.LogDebug($"Params: userId={user.Id}");

        IList<Claim> claims = await userManager.GetClaimsAsync(user);

        return claims;
    }

    /// <summary>
    /// Checks if a user is in the role
    /// </summary>
    /// <param name="id">ID of the user</param>
    /// <param name="role">Name of the role to check</param>
    /// <returns>True/False if user is in role</returns>
    public async Task<bool> IsInRoleAsync(AppUser user, string role)
    {
        logger.LogDebug($"Params: userId={user.Id}, role={role}");

        return await userManager.IsInRoleAsync(user, role);
    }

    /// <summary>
    /// Generates a password reset token for the user
    /// </summary>
    /// <param name="user">User</param>
    /// <returns>Password reset token</returns>
    public async Task<string> GeneratePasswordResetTokenAsync(AppUser user)
    {
        logger.LogDebug($"Params: userId={user.Id}");

        return await userManager.GeneratePasswordResetTokenAsync(user);
    }

    /// <summary>
    /// Resets the user's password
    /// </summary>
    /// <param name="user">The user whose password should be reset.</param>
    /// <param name="token">The password reset token to verify.</param>
    /// <param name="newPassword">The new password to set if reset token verification succeeds.</param>
    /// <returns>Result with Empty</returns>
    public async Task<Result<Empty>> ResetPasswordAsync(AppUser user, string token, string newPassword)
    {
        logger.LogDebug($"Params: userId={user.Id}");

        IdentityResult result = await userManager.ResetPasswordAsync(user, token, newPassword);
        if (!result.Succeeded)
        {
            return Failed(result, "Error resetting password");
        }

        return Result.Success<Empty>();
    }

    /// <summary>
    /// Updates a user
    /// </summary>
    /// <param name="user">User to save</param>
    /// <returns>Result with Empty</returns>
    public async Task<Result<Empty>> UpdateUserAsync(AppUser user)
    {
        IdentityResult result = await userManager.UpdateAsync(user);
        if (!result.Succeeded)
        {
            return Failed(result, "Error updating user");
        }

        return Result.Success<Empty>();
    }

    /// <summary>
    /// Generates a failed result
    /// </summary>
    /// <param name="result">IdentityResult</param>
    /// <param name="messagePrefix">Message to add to the log</param>
    /// <returns>Empty result with error message</returns>
    private Result<Empty> Failed(IdentityResult result, string messagePrefix)
    {
        string errors = LogIdentityResultErrors(result, messagePrefix);
        string message = $"{messagePrefix} - {errors.ToString().Trim()}";

        return Result.Failed<Empty>(message);
    }

    /// <summary>
    /// Logs any errors generated by the identity result
    /// </summary>
    /// <param name="result">IdentityResult</param>
    /// <param name="messagePrefix">Message to add to the log</param>
    /// <returns>Errors</returns>
    private string LogIdentityResultErrors(IdentityResult result, string messagePrefix)
    {
        StringBuilder errors = new();
        result.Errors.ToList().ForEach(e => errors.Append(e.Description.Trim() + " "));
        string message = $"{messagePrefix} - {errors.ToString().Trim()}";

        logger.LogError(message);

        return errors.ToString().Trim();
    }
}
